This builds successfully. Broke out the external toolchain part of the build script in order to reduce the overall size of buildmistify itself.

diff --git a/buildmistify b/buildmistify
--- a/buildmistify
+++ b/buildmistify
@@ -5,32 +5,7 @@
 # The intent is to use a copy of the Buildroot build envirnment for Buildroot 
 # unmodified and using an external project directory.
 #-
-green='\e[0;32m'
-yellow='\e[0;33m'
-red='\e[0;31m'
-blue='\e[0;34m'
-lightblue='\e[1;34m'
-white='\e[1;37m'
-nc='\e[0m'
-prefix="buildmistify"
 
-projectdir=$PWD	# Save this directory for later.
-# Where to maintain buildmistify settings.
-statedir=$projectdir/.buildmistify
-
-#+
-# Defaults
-#-
-
-#+
-# TODO: toolchaintag needs to be updated at release time to use the tag corresponding
-# to the release.
-#-
-tcuridefault=git://crosstool-ng.org/crosstool-ng
-toolchaindirdefault=$PWD/toolchain
-toolchainprefixdefault=x86_64-unknown-linux-gnu
-toolchainbranchdefault="master"
-toolchaintagdefault=
 
 #+
 # TODO: buildroottag needs to be updated at release time to use the tag corresponding
@@ -46,7 +21,6 @@ downloaddirdefault=$PWD/downloads
 mistifycfgdefault=$PWD/configs/mistify_defconfig
 kernelcfgdefault=$PWD/configs/mistify-kernel.config
 busyboxcfgdefault=$PWD/configs/mistify-busybox.config
-
 
 usage () {
     cat << EOF
@@ -137,6 +111,11 @@ Usage: ./buildmistify [options] [target]
         directory before running the buildroot make. The file name is saved in 
         the file $statedir/bbconfig.
         [bbconfig=`cat $statedir/bbconfig 2>/dev/null || echo \\`]
+    --tcconfig
+        Use this toolchain config file. The config file is copied to the
+        toolchain build directory before running the toolchain build. The file
+        name is saved in the file $statedir/tcconfig.
+        [tcconfig=`cat $statedir/tcconfig 2>/dev/null || echo \\`]
     ==== other ====
     -l|--logfile
         Use this log file name instead of the generated log file name.
@@ -147,9 +126,20 @@ Usage: ./buildmistify [options] [target]
         make.
     -h|--help
         Display this usage.
+    ==== special targets ====
+    toolchain-menuconfig
+        Run the toolchain configuration utility.
+    menuconfig
+        Run the Buildroot configuration utility.
+    busybox-menuconfig
+        Run the Busybox configuration utility.
+    linux-menuconfig
+        Run the Linux kernel configuration utility.
+
   NOTE: This script maintains state in $statedir.
-  The targets menuconfig and linux-menuconfig exit immediately after exiting the
-  corresponding configuration utilities.
+  The targets toolchain-menuconfig, menuconfig, busybox-menuconfig and
+  linux-menuconfig exit immediately after exiting the corresponding
+  configuration utilities.
   Custom environment variables:
     MISTIFY_DIR = Points to the directory in which buildmistify resides. This
     can then be used in the buildroot config to specify locations of files such
@@ -157,184 +147,8 @@ Usage: ./buildmistify [options] [target]
 EOF
 }
 
-message () {
-    echo -e "$green$prefix$nc: $*"
-}
-
-tip () {
-    echo -e "$green$prefix$nc: $white$*$nc"
-}
-
-warning () {
-    echo -e "$green$prefix$yellow WARNING$nc: $*"
-}
-
-error () {
-    echo -e "$green$prefix$red ERROR$nc: $*"
-}
-
-install-toolchain () {
-    #+
-    # Determine the location of the toolchain directory.
-    #-
-    if [ -z "$toolchaindir" ]; then
-	if [ -f $statedir/toolchaindir ]; then
-	    toolchaindir=`cat $statedir/toolchaindir`
-	else
-	    toolchaindir=$toolchaindirdefault
-	fi
-	message "Using toolchain located at: $toolchaindir"
-    fi
-    echo $toolchaindir >$statedir/toolchaindir
-    #+
-    # Determine the toolchain variation to use.
-    #-
-    if [ -z "$toolchainprefix" ]; then
-	if [ -f $statedir/toolchainprefix ]; then
-	    toolchainprefix=`cat $statedir/toolchainprefix`
-	else
-	    toolchainprefix=$toolchainprefixdefault
-	fi
-	message "Using toolchain variation: $toolchainprefix"
-    fi
-    echo $toolchainprefix >$statedir/toolchainprefix
-    #+
-    # Start by fetching the Buildroot build environment.
-    #-
-    if [ -z "$tcuri" ]; then
-	if [ -f $statedir/tcuri ]; then
-	    tcuri=`cat $statedir/tcuri`
-	else
-	    tcuri=$tcuridefault
-	fi
-    fi
-    message "The toolchain build tool repository is: $tcuri"
-    echo $tcuri >$statedir/tcuri
-
-    #+
-    # If the toolchainbranch option is used then ignore the toolchaintag option.
-    # NOTE: Specifying a branch overrides using a tag.
-    #-
-    if [ ! -z "$toolchainbranch" ]; then
-	message "Switching to toolchain build tool branch: $toolchainbranch"
-	if [ ! -z "$toolchaintag" ]; then
-	    warning "Ignoring --toolchaintag"
-	    toolchaintag=
-	fi
-	rm -f $statedir/toolchaintag
-    else
-	if [ -f $statedir/toolchainbranch ]; then
-	    toolchainbranch=`cat $statedir/toolchainbranch`
-	else
-	    toolchainbranch=$toolchainbranchdefault
-	fi
-    fi
-    echo $toolchainbranch >$statedir/toolchainbranch
-
-    if [ ! -f $toolchaindir/README ]; then
-	message 'Fetching toolchain build tool branch "master" from the toolchain repository.'
-	git clone $tcuri $toolchaindir
-	#+
-	# TODO: It is possible that the previous clone failed. Might want to use
-	# git again to update just in case.
-	#-
-	if [ $? -gt 0 ]; then
-	    error "Fetching the toolchain encountered an error."
-	    exit 1
-	fi
-    fi
-    cd $toolchaindir
-
-    #+
-    # Determine the tag to use to sync toolchain to.
-    # NOTE: Having branch and tag separate helps avoid an ambiguity which could
-    # result in accidentally creating a branch when a tag was intended.
-    # NOTE: If toolchaintag is set at this point then it wasn't overridden by  
-    # specifying a branch.
-    #-
-    if [ ! -z "$toolchaintag" ]; then
-	buildrootbranch=
-	message "Switching to toolchain build tool tag: $toolchaintag"
-	echo $toolchaintag >$statedir/buildroottag
-	else
-	if [ -f $statedir/toolchaintag ]; then
-	    toolchainbranch=
-	    toolchaintag=`cat $statedir/toolchaintag`
-	fi
-    fi
-
-    #+
-    # Verify using the desired toolchain version. If the branch or tag doesn't exist
-    # locally then fetch an update from the repo.
-    #-
-    if [ ! -z "$toolchaintag" ]; then
-	message "Using toolchain tag: $toolchaintag"
-	git tag | grep $toolchaintag
-	if [ $? -ne 0 ]; then
-	    message "Local toolchain build tool tag $toolchaintag doesn't exist."
-	    message "Fetching toolchain update from remote repository."
-	    git fetch
-	fi
-	toolchainlabel="tags/$toolchaintag"
-    else
-	message "Using toolchain build tool branch: $toolchainbranch"
-	git branch | grep $toolchainbranch
-	if [ $? -ne 0 ]; then
-	    message "Local toolchain branch $toolchainbranch doesn't exist."
-	    message "Fetching update from remote toolchain repository."
-	    git fetch
-	fi
-	toolchainlabel=$toolchainbranch
-    fi
-
-    git checkout $toolchainlabel
-    if [ $? -ne 0 ]; then
-	error "Attempted to checkout the toolchain build tool using an invalid tag or branch: $toolchainlabel"
-	exit 1
-    fi
-    message "The toolchain build tool synced to: $toolchainlabel"
-    #+
-    # These variables are used within the crosstool-ng config file which helps
-    # avoid having to modify the config when changing toolchain branches or
-    # tags.
-    #-
-    export TC_ARCH_SUFFIX=-$toolchainlabel
-    export TC_PREFIX_DIR=$toolchaindir/variations/$toolchainlabel
-    export TC_LOCAL_TARBALLS_DIR=$downloaddir
-    message "TC_ARCH_SUFFIX: $TC_ARCH_SUFFIX"
-    message "TC_PREFIX_DIR: $TC_PREFIX_DIR"
-    message "TC_LOCAL_TARBALLS_DIR: $TC_LOCAL_TARBALLS_DIR"
-
-    if [ -f $TC_PREFIX_DIR/../.$toolchainlabel-built ]; then
-	message "Using toolchain installed at: $TC_PREFIX_DIR"
-	#+
-	# TODO: Sync to the desired branch or tag.
-	#-
-	return
-    fi
-    #+
-    # Download, build and install the toolchain.
-    #-
-    message "Toolchain not detected."
-    message "Installing toolchain to: $TC_PREFIX_DIR"
-    #+
-    # Now configure and build the toolchain.
-    #-
-    cd $toolchaindir
-    ./bootstrap
-    ./configure --enable-local --prefix=$toolchaindir
-    make
-    
-    ctng="./ct-ng"
-    cp $projectdir/configs/mistify-tc.config .config
-    mkdir -p $TC_LOCAL_TARBALLS_DIR
-    $ctng build
-    if [ $? -gt 0 ]; then
-	error "The toolchain build failed."
-	exit 1
-    fi
-    touch $TC_PREFIX_DIR/../.$toolchainlabel-built
-}
+source scripts/mistify-functions.sh
+source scripts/install-toolchain.sh
 
 #+
 # TODO: Add some quick checks to verify required tools are installed.
@@ -357,6 +171,7 @@ builddir:,\
 config:,\
 kconfig:,\
 bbconfig:,\
+tcconfig:,\
 test,\
 downloaddir:,\
 logfile:,\
@@ -433,6 +248,10 @@ while [ $# -ge 1 ]; do
 	    busyboxcfg=$2
 	    shift
 	    ;;
+	--tcconfig)
+	    tcconfig=$2
+	    shift
+	    ;;
 	-l|--logfile)
 	    logfilename=$2
 	    shift
@@ -504,7 +323,7 @@ message "Build output directory is: $builddir"
 echo $builddir >$statedir/builddir
 
 #+
-# Start by fetching the Buildroot build environment.
+# Determine the uri to use to fetch the Buildroot tool.
 #-
 if [ -z "$bruri" ]; then
   if [ -f $statedir/bruri ]; then
@@ -610,7 +429,11 @@ if [ -z "$mistifycfg" ]; then
     mistifycfg=$mistifycfgdefault
   fi
 fi
+
+buildrootkernelheaders=`grep BR2_LINUX_KERNEL_VERSION $mistifycfg | cut -d \" -f 2`
+
 message "The Buildroot config file is: $mistifycfg"
+message "The kernel headers version is: $buildrootkernelheaders"
 
 brc=$builddir/.config
 if [ -f $mistifycfg ]; then
@@ -731,73 +554,74 @@ makecommand="\
 make O=$builddir \
 TOOLCHAIN_PATH=$TC_PREFIX_DIR TOOLCHAIN_PREFIX=$toolchainprefix \
 BR2_DL_DIR=$downloaddir BR2_EXTERNAL=$projectdir \
+BR2_DEFAULT_KERNEL_HEADERS=$buildrootkernelheaders \
 $target"
 
 #+
 # Don't run the build if changing configurations.
 #-
 case "$target" in
-  "menuconfig" | "nconfig")
-    $makecommand
-    if [[ ! -f $mistifycfg || $brc -nt $mistifycfg ]]; then
-    #+
-    # NOTE: The buildroot config option BR2_DEFCONFIG
-    # needs to point to the config file so that buildroot will copy the correct
-    # file on the first build.
-    #-
-      cp $brc $mistifycfg
-      if [ $? -gt 0 ]; then
-        error "Failed to save $mistifycfg"
-        exit 1
-      fi
-      tip "Use $0 to build Mistify using the new configuration."
-      message "New config file at $brc saved to $mistifycfg"
-    fi
-    exit
-    ;;
-  "xconfig" | "gconfig")
-    error "Configuration tool $target is not supported."
-    exit 1
-    ;;
-  "linux-menuconfig")
-    #+
-    # NOTE: The buildroot config option BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE
-    # needs to point to the config file so that buildroot will copy the correct
-    # file on the first build.
-    #-
-    $makecommand
-    if [[ ! -f $kernelcfg || $brkc -nt $kernelcfg ]]; then
-      cp $brkc $kernelcfg
-      if [ $? -gt 0 ]; then
-        error "Failed to save $kernelcfg"
-        exit 1
-      fi
-      tip "Use $0 to build Mistify using the new configuration."
-      message "New kernel config file at $brkc saved to $kernelcfg"
-    fi
-    exit
-    ;;
-  "busybox-menuconfig")
-    #+
-    # NOTE: The buildroot config option BR2_PACKAGE_BUSYBOX_CONFIG
-    # needs to point to the config file so that buildroot will copy the correct
-    # file on the first build.
-    #-
-    $makecommand
-    # NOTE: May want to use grep instead of a timestamp compare.
-    if [[ ! -f $busyboxcfg || $bbc -nt $busyboxcfg ]]; then
-      cp $bbc $busyboxcfg
-      if [ $? -gt 0 ]; then
-        error "Failed to save $busyboxcfg"
-        exit 1
-      fi
-      tip "Use $0 to build Mistify using the new configuration."
-      message "New BusyBox config file $bbc saved to $busyboxcfg"
-    fi
-    exit
-    ;;
-  *)
-    ;;
+    "menuconfig" | "nconfig")
+	$makecommand
+	if [[ ! -f $mistifycfg || $brc -nt $mistifycfg ]]; then
+	    #+
+	    # NOTE: The buildroot config option BR2_DEFCONFIG
+	    # needs to point to the config file so that buildroot will copy the correct
+	    # file on the first build.
+	    #-
+	    cp $brc $mistifycfg
+	    if [ $? -gt 0 ]; then
+		error "Failed to save $mistifycfg"
+		exit 1
+	    fi
+	    tip "Use $0 to build Mistify using the new configuration."
+	    message "New config file at $brc saved to $mistifycfg"
+	fi
+	exit
+	;;
+    "xconfig" | "gconfig")
+	error "Configuration tool $target is not supported."
+	exit 1
+	;;
+    "linux-menuconfig")
+	#+
+	# NOTE: The buildroot config option BR2_LINUX_KERNEL_CUSTOM_CONFIG_FILE
+	# needs to point to the config file so that buildroot will copy the correct
+	# file on the first build.
+	#-
+	$makecommand
+	if [[ ! -f $kernelcfg || $brkc -nt $kernelcfg ]]; then
+	    cp $brkc $kernelcfg
+	    if [ $? -gt 0 ]; then
+		error "Failed to save $kernelcfg"
+		exit 1
+	    fi
+	    tip "Use $0 to build Mistify using the new configuration."
+	    message "New kernel config file at $brkc saved to $kernelcfg"
+	fi
+	exit
+	;;
+    "busybox-menuconfig")
+	#+
+	# NOTE: The buildroot config option BR2_PACKAGE_BUSYBOX_CONFIG
+	# needs to point to the config file so that buildroot will copy the correct
+	# file on the first build.
+	#-
+	$makecommand
+	# NOTE: May want to use grep instead of a timestamp compare.
+	if [[ ! -f $busyboxcfg || $bbc -nt $busyboxcfg ]]; then
+	    cp $bbc $busyboxcfg
+	    if [ $? -gt 0 ]; then
+		error "Failed to save $busyboxcfg"
+		exit 1
+	    fi
+	    tip "Use $0 to build Mistify using the new configuration."
+	    message "New BusyBox config file $bbc saved to $busyboxcfg"
+	fi
+	exit
+	;;
+    *)
+	;;
 esac
 
 #+
